version: '3.9'
services: 
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic

  petclinic-app:
    build:  .
    container_name: petclinic-app
    environment:
      spring.datasource.url: "jdbc:mysql://mysql:3306/petclinic"
      spring.datasource.username: petclinic
      spring.datasource.password: petclinic
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
